"""Generate drl_assignment2.ipynb from drl_assignment2.py."""
import json
from pathlib import Path

def md(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }

cells = []

# ── Title ──────────────────────────────────────────────────────────────────
cells.append(md(
    "# DRL Assignment II — DQN vs DDQN on LunarLander\n\n"
    "**Robust Reinforcement Learning under Stochastic Action Failure**\n\n"
    "This notebook implements and compares four agents:\n\n"
    "| Algorithm | Environment |\n"
    "|-----------|-------------|\n"
    "| DQN  | Original `LunarLander-v3` |\n"
    "| DDQN | Original `LunarLander-v3` |\n"
    "| DQN  | Stochastic action-failure wrapper (15% failure rate) |\n"
    "| DDQN | Stochastic action-failure wrapper (15% failure rate) |\n\n"
    "Run cells top-to-bottom. Use the **Run Experiments** section at the bottom to "
    "trigger verification, training, or plotting."
))

# ── Imports ────────────────────────────────────────────────────────────────
cells.append(md("## 0 — Imports"))
cells.append(code(
    "from __future__ import annotations\n"
    "\n"
    "import argparse\n"
    "import csv\n"
    "import json\n"
    "import random\n"
    "from collections import deque\n"
    "from dataclasses import asdict, dataclass\n"
    "from pathlib import Path\n"
    "from typing import Any, Deque, Literal\n"
    "\n"
    "import gymnasium as gym\n"
    "import matplotlib.pyplot as plt\n"
    "import numpy as np\n"
    "import torch\n"
    "from torch import nn\n"
    "\n"
    "print(f'PyTorch {torch.__version__} | Gymnasium {gym.__version__}')"
))

# ── Section 1: Custom Environment ──────────────────────────────────────────
cells.append(md(
    "## 1 — Custom Environment Wrapper\n\n"
    "Wraps `LunarLander-v3` to introduce:\n"
    "- **15% action failure**: a requested thruster action (1, 2, 3) silently becomes action 0.\n"
    "- **Fuel penalty**: `−0.3` per *requested* thruster action, even if it misfires.\n"
    "- **Safe-landing bonus**: `+50` when both legs contact with low velocity and near-level orientation.\n\n"
    "> The failure is hidden from the agent — `info` is unchanged."
))
cells.append(code(
    "@dataclass\n"
    "class FailureStatistics:\n"
    "    \"\"\"Counters used to verify the wrapper without exposing data to the agent.\"\"\"\n"
    "    attempted_thruster_actions: int = 0\n"
    "    failed_thruster_actions: int = 0\n"
    "    attempted_fuel_penalty: float = 0.0\n"
    "    safe_landing_bonus_count: int = 0\n"
    "\n"
    "    @property\n"
    "    def observed_failure_rate(self) -> float:\n"
    "        \"\"\"Return the fraction of attempted thruster actions that misfired.\"\"\"\n"
    "        if self.attempted_thruster_actions == 0:\n"
    "            return 0.0\n"
    "        return self.failed_thruster_actions / self.attempted_thruster_actions\n"
    "\n"
    "\n"
    "class StochasticFailureLunarLander(gym.Wrapper):\n"
    "    \"\"\"Apply intermittent engine failure and modified rewards to LunarLander.\n\n"
    "    A requested thruster action (1, 2, or 3) has a 15% probability of becoming\n"
    "    action 0. The fuel penalty is based on the action requested by the agent,\n"
    "    even if that action subsequently fails.\n"
    "    \"\"\"\n"
    "    FAILURE_PROBABILITY = 0.15\n"
    "    FUEL_PENALTY = 0.3\n"
    "    SAFE_LANDING_BONUS = 50.0\n"
    "    VELOCITY_LIMIT = 0.10\n"
    "    ANGLE_LIMIT = 0.10\n"
    "\n"
    "    def __init__(self, env: gym.Env):\n"
    "        \"\"\"Wrap an existing LunarLander-v3 environment.\"\"\"\n"
    "        super().__init__(env)\n"
    "        self.statistics = FailureStatistics()\n"
    "\n"
    "    def reset_statistics(self) -> None:\n"
    "        \"\"\"Clear verification counters before a new experiment.\"\"\"\n"
    "        self.statistics = FailureStatistics()\n"
    "\n"
    "    def _sample_executed_action(self, selected_action: int) -> int:\n"
    "        \"\"\"Return the action the base environment will execute.\"\"\"\n"
    "        if selected_action == 0:\n"
    "            return 0\n"
    "        self.statistics.attempted_thruster_actions += 1\n"
    "        if self.np_random.random() < self.FAILURE_PROBABILITY:\n"
    "            self.statistics.failed_thruster_actions += 1\n"
    "            return 0\n"
    "        return selected_action\n"
    "\n"
    "    def _safe_landing(self, observation: np.ndarray, terminated: bool, truncated: bool) -> bool:\n"
    "        \"\"\"Return whether the final state meets every safe-landing condition.\"\"\"\n"
    "        return bool(\n"
    "            terminated\n"
    "            and not truncated\n"
    "            and observation[6] == 1\n"
    "            and observation[7] == 1\n"
    "            and abs(observation[2]) < self.VELOCITY_LIMIT\n"
    "            and abs(observation[3]) < self.VELOCITY_LIMIT\n"
    "            and abs(observation[4]) < self.ANGLE_LIMIT\n"
    "        )\n"
    "\n"
    "    def step(self, action: int) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:\n"
    "        \"\"\"Execute a possibly failed action and return the specified reward.\"\"\"\n"
    "        selected_action = int(action)\n"
    "        if not self.action_space.contains(selected_action):\n"
    "            raise ValueError(f'Invalid LunarLander action: {selected_action}')\n"
    "        executed_action = self._sample_executed_action(selected_action)\n"
    "        observation, base_reward, terminated, truncated, info = self.env.step(executed_action)\n"
    "        fuel_penalty = self.FUEL_PENALTY if selected_action in (1, 2, 3) else 0.0\n"
    "        self.statistics.attempted_fuel_penalty += fuel_penalty\n"
    "        landing_bonus = 0.0\n"
    "        if self._safe_landing(observation, terminated, truncated):\n"
    "            landing_bonus = self.SAFE_LANDING_BONUS\n"
    "            self.statistics.safe_landing_bonus_count += 1\n"
    "        modified_reward = float(base_reward - fuel_penalty + landing_bonus)\n"
    "        return observation, modified_reward, terminated, truncated, info\n"
    "\n"
    "print('StochasticFailureLunarLander defined.')"
))

# ── Section 2: Q-Network ──────────────────────────────────────────────────
cells.append(md(
    "## 2 — Q-Network Architecture\n\n"
    "A two-hidden-layer MLP (128 → 128) maps an 8-dimensional state to "
    "4 Q-values (one per action). ReLU activations allow non-linear policy learning."
))
cells.append(code(
    "class QNetwork(nn.Module):\n"
    "    \"\"\"Map a state vector to one predicted Q-value per discrete action.\"\"\"\n"
    "\n"
    "    def __init__(self, state_size: int, action_size: int, hidden_size: int = 128) -> None:\n"
    "        \"\"\"Build a two-hidden-layer fully connected Q-network.\"\"\"\n"
    "        super().__init__()\n"
    "        # ReLU allows the network to learn non-linear landing-control patterns.\n"
    "        self.layers = nn.Sequential(\n"
    "            nn.Linear(state_size, hidden_size),\n"
    "            nn.ReLU(),\n"
    "            nn.Linear(hidden_size, hidden_size),\n"
    "            nn.ReLU(),\n"
    "            nn.Linear(hidden_size, action_size),\n"
    "        )\n"
    "\n"
    "    def forward(self, states: torch.Tensor) -> torch.Tensor:\n"
    "        \"\"\"Return Q-values with shape (batch_size, action_size).\"\"\"\n"
    "        return self.layers(states)\n"
    "\n"
    "print('QNetwork defined. Parameters:', sum(p.numel() for p in QNetwork(8, 4).parameters()))"
))

# ── Section 3: Replay Buffer ───────────────────────────────────────────────
cells.append(md(
    "## 3 — Experience Replay Buffer\n\n"
    "Stores `(state, action, reward, next_state, done)` tuples in a fixed-size deque. "
    "Random mini-batch sampling breaks temporal correlation between consecutive steps, "
    "stabilising gradient updates."
))
cells.append(code(
    "@dataclass(frozen=True)\n"
    "class Transition:\n"
    "    \"\"\"One learning experience collected from a single environment step.\"\"\"\n"
    "    state: np.ndarray\n"
    "    action: int\n"
    "    reward: float\n"
    "    next_state: np.ndarray\n"
    "    done: bool\n"
    "\n"
    "\n"
    "class ReplayBuffer:\n"
    "    \"\"\"Store experiences and return random batches for neural-network training.\"\"\"\n"
    "\n"
    "    def __init__(self, capacity: int, seed: int) -> None:\n"
    "        if capacity <= 0:\n"
    "            raise ValueError('Replay-buffer capacity must be positive.')\n"
    "        self.memory: Deque[Transition] = deque(maxlen=capacity)\n"
    "        self.random_generator = np.random.default_rng(seed)\n"
    "\n"
    "    def add(self, state, action, reward, next_state, done) -> None:\n"
    "        \"\"\"Copy and save one transition so later mutation cannot corrupt it.\"\"\"\n"
    "        transition = Transition(\n"
    "            state=np.asarray(state, dtype=np.float32).copy(),\n"
    "            action=int(action),\n"
    "            reward=float(reward),\n"
    "            next_state=np.asarray(next_state, dtype=np.float32).copy(),\n"
    "            done=bool(done),\n"
    "        )\n"
    "        self.memory.append(transition)\n"
    "\n"
    "    def sample(self, batch_size: int):\n"
    "        \"\"\"Return a random batch as NumPy arrays ready for PyTorch tensors.\"\"\"\n"
    "        if batch_size > len(self.memory):\n"
    "            raise ValueError('Cannot sample more transitions than are stored.')\n"
    "        indices = self.random_generator.choice(len(self.memory), batch_size, replace=False)\n"
    "        batch = [self.memory[i] for i in indices]\n"
    "        states      = np.stack([t.state      for t in batch])\n"
    "        actions     = np.asarray([t.action   for t in batch], dtype=np.int64)\n"
    "        rewards     = np.asarray([t.reward   for t in batch], dtype=np.float32)\n"
    "        next_states = np.stack([t.next_state for t in batch])\n"
    "        dones       = np.asarray([t.done     for t in batch], dtype=np.float32)\n"
    "        return states, actions, rewards, next_states, dones\n"
    "\n"
    "    def __len__(self) -> int:\n"
    "        return len(self.memory)\n"
    "\n"
    "print('ReplayBuffer defined.')"
))

# ── Section 4: DQN Agent ───────────────────────────────────────────────────
cells.append(md(
    "## 4 — DQN Agent\n\n"
    "Standard Deep Q-Network with:\n"
    "- **Online network** — updated every step via gradient descent\n"
    "- **Target network** — frozen copy, synced every `target_update_interval` steps\n"
    "- **Epsilon-greedy** exploration\n"
    "- **Gradient clipping** (`max_norm=10`) for stability\n\n"
    "**Target Q formula (DQN):**\n"
    "```\n"
    "y = r + γ · max_a' Q_target(s', a')\n"
    "```\n"
    "The *target network* selects **and** evaluates the best next action."
))
cells.append(code(
    "@dataclass(frozen=True)\n"
    "class DQNConfig:\n"
    "    \"\"\"Hyperparameters shared by DQN and DDQN for a fair experiment.\"\"\"\n"
    "    state_size: int = 8\n"
    "    action_size: int = 4\n"
    "    hidden_size: int = 128\n"
    "    replay_capacity: int = 100_000\n"
    "    batch_size: int = 64\n"
    "    learning_rate: float = 1e-3\n"
    "    discount_factor: float = 0.99\n"
    "    target_update_interval: int = 1_000\n"
    "\n"
    "\n"
    "class DQNAgent:\n"
    "    \"\"\"Learn action values with experience replay and a target network.\"\"\"\n"
    "\n"
    "    def __init__(self, config: DQNConfig, seed: int, device: torch.device) -> None:\n"
    "        self.config = config\n"
    "        self.device = device\n"
    "        self.random_generator = np.random.default_rng(seed)\n"
    "        # Both networks start identically; only the online network is optimized.\n"
    "        self.online_network = QNetwork(config.state_size, config.action_size, config.hidden_size).to(device)\n"
    "        self.target_network = QNetwork(config.state_size, config.action_size, config.hidden_size).to(device)\n"
    "        self.update_target_network()\n"
    "        self.target_network.eval()\n"
    "        self.optimizer = torch.optim.Adam(self.online_network.parameters(), lr=config.learning_rate)\n"
    "        self.loss_function = nn.SmoothL1Loss()\n"
    "        self.replay_buffer = ReplayBuffer(config.replay_capacity, seed)\n"
    "        self.learning_steps = 0\n"
    "\n"
    "    def select_action(self, state: np.ndarray, epsilon: float) -> int:\n"
    "        \"\"\"Choose a random action with probability epsilon; otherwise exploit.\"\"\"\n"
    "        if not 0.0 <= epsilon <= 1.0:\n"
    "            raise ValueError('Epsilon must be between 0 and 1.')\n"
    "        if self.random_generator.random() < epsilon:\n"
    "            return int(self.random_generator.integers(self.config.action_size))\n"
    "        state_tensor = torch.as_tensor(state, dtype=torch.float32, device=self.device)\n"
    "        with torch.no_grad():\n"
    "            q_values = self.online_network(state_tensor.unsqueeze(0))\n"
    "        return int(torch.argmax(q_values, dim=1).item())\n"
    "\n"
    "    def store_transition(self, state, action, reward, next_state, done) -> None:\n"
    "        \"\"\"Save a completed environment interaction in replay memory.\"\"\"\n"
    "        self.replay_buffer.add(state, action, reward, next_state, done)\n"
    "\n"
    "    def learn(self) -> float | None:\n"
    "        \"\"\"Perform one gradient update when enough experiences are available.\"\"\"\n"
    "        if len(self.replay_buffer) < self.config.batch_size:\n"
    "            return None\n"
    "        states, actions, rewards, next_states, dones = self.replay_buffer.sample(self.config.batch_size)\n"
    "        s  = torch.as_tensor(states,      dtype=torch.float32, device=self.device)\n"
    "        a  = torch.as_tensor(actions,      dtype=torch.int64,   device=self.device)\n"
    "        r  = torch.as_tensor(rewards,      dtype=torch.float32, device=self.device)\n"
    "        ns = torch.as_tensor(next_states,  dtype=torch.float32, device=self.device)\n"
    "        d  = torch.as_tensor(dones,        dtype=torch.float32, device=self.device)\n"
    "        # Select the online-network value for the action actually taken.\n"
    "        predicted_q = self.online_network(s).gather(1, a.unsqueeze(1)).squeeze(1)\n"
    "        with torch.no_grad():\n"
    "            # DQN: target network selects AND evaluates the best next action.\n"
    "            next_q = self.target_network(ns).max(dim=1).values\n"
    "            target_q = r + self.config.discount_factor * (1.0 - d) * next_q\n"
    "        loss = self.loss_function(predicted_q, target_q)\n"
    "        self.optimizer.zero_grad()\n"
    "        loss.backward()\n"
    "        # Gradient clipping prevents a rare large update from destabilizing learning.\n"
    "        torch.nn.utils.clip_grad_norm_(self.online_network.parameters(), max_norm=10.0)\n"
    "        self.optimizer.step()\n"
    "        self.learning_steps += 1\n"
    "        if self.learning_steps % self.config.target_update_interval == 0:\n"
    "            self.update_target_network()\n"
    "        return float(loss.item())\n"
    "\n"
    "    def update_target_network(self) -> None:\n"
    "        \"\"\"Copy online-network weights to the delayed target network.\"\"\"\n"
    "        self.target_network.load_state_dict(self.online_network.state_dict())\n"
    "\n"
    "    def mean_q_value(self, states: np.ndarray) -> float:\n"
    "        \"\"\"Return mean predicted Q-value over a fixed validation-state set.\"\"\"\n"
    "        t = torch.as_tensor(states, dtype=torch.float32, device=self.device)\n"
    "        with torch.no_grad():\n"
    "            return float(self.online_network(t).mean().item())\n"
    "\n"
    "print('DQNAgent defined.')"
))

# ── Section 5: DDQN Agent ──────────────────────────────────────────────────
cells.append(md(
    "## 5 — Double DQN Agent\n\n"
    "Inherits everything from `DQNAgent`. The **only** difference is how the target Q-value is computed:\n\n"
    "```\n"
    "DQN:  y = r + γ · Q_target(s', argmax_a' Q_target(s', a'))  ← one network does both jobs\n"
    "DDQN: y = r + γ · Q_target(s', argmax_a' Q_online(s', a'))  ← online selects, target evaluates\n"
    "```\n\n"
    "This decoupling reduces overestimation bias, which becomes especially important "
    "under stochastic action failures."
))
cells.append(code(
    "class DDQNAgent(DQNAgent):\n"
    "    \"\"\"DQN agent whose only behavioral difference is the target-Q calculation.\"\"\"\n"
    "\n"
    "    def learn(self) -> float | None:\n"
    "        \"\"\"Perform one DDQN update when enough replay data is available.\"\"\"\n"
    "        if len(self.replay_buffer) < self.config.batch_size:\n"
    "            return None\n"
    "        states, actions, rewards, next_states, dones = self.replay_buffer.sample(self.config.batch_size)\n"
    "        s  = torch.as_tensor(states,     dtype=torch.float32, device=self.device)\n"
    "        a  = torch.as_tensor(actions,     dtype=torch.int64,   device=self.device)\n"
    "        r  = torch.as_tensor(rewards,     dtype=torch.float32, device=self.device)\n"
    "        ns = torch.as_tensor(next_states, dtype=torch.float32, device=self.device)\n"
    "        d  = torch.as_tensor(dones,       dtype=torch.float32, device=self.device)\n"
    "        predicted_q = self.online_network(s).gather(1, a.unsqueeze(1)).squeeze(1)\n"
    "        with torch.no_grad():\n"
    "            # DDQN selection: online network decides which next action is best.\n"
    "            next_actions = self.online_network(ns).argmax(dim=1, keepdim=True)\n"
    "            # DDQN evaluation: target network scores that already selected action.\n"
    "            next_q = self.target_network(ns).gather(1, next_actions).squeeze(1)\n"
    "            target_q = r + self.config.discount_factor * (1.0 - d) * next_q\n"
    "        loss = self.loss_function(predicted_q, target_q)\n"
    "        self.optimizer.zero_grad()\n"
    "        loss.backward()\n"
    "        # This stabilization setting is intentionally identical to DQN's.\n"
    "        torch.nn.utils.clip_grad_norm_(self.online_network.parameters(), max_norm=10.0)\n"
    "        self.optimizer.step()\n"
    "        self.learning_steps += 1\n"
    "        if self.learning_steps % self.config.target_update_interval == 0:\n"
    "            self.update_target_network()\n"
    "        return float(loss.item())\n"
    "\n"
    "print('DDQNAgent defined.')"
))

# ── Section 6: Training Pipeline ───────────────────────────────────────────
cells.append(md(
    "## 6 — Training Pipeline\n\n"
    "Trains all four agent/environment combinations with identical seeds, "
    "architecture, optimizer, and exploration schedule. "
    "Saves model weights (`.pt`), metrics (`.npz`), and settings (`.json`) under `outputs/`."
))
cells.append(code(
    "AlgorithmName = Literal['dqn', 'ddqn']\n"
    "EnvironmentName = Literal['original', 'modified']\n"
    "OUTPUT_DIRECTORY = Path('outputs')\n"
    "\n"
    "\n"
    "@dataclass(frozen=True)\n"
    "class TrainingConfig:\n"
    "    \"\"\"Experiment settings that remain identical across all four agents.\"\"\"\n"
    "    episodes: int = 700\n"
    "    max_steps_per_episode: int = 1_000\n"
    "    seed: int = 2026\n"
    "    epsilon_start: float = 1.0\n"
    "    epsilon_end: float = 0.05\n"
    "    epsilon_decay_episodes: int = 500\n"
    "    validation_state_count: int = 512\n"
    "    success_window: int = 100\n"
    "\n"
    "\n"
    "@dataclass\n"
    "class TrainingMetrics:\n"
    "    \"\"\"Per-episode values required for the final performance plots.\"\"\"\n"
    "    episode_rewards: list[float]\n"
    "    average_predicted_q_values: list[float]\n"
    "    successful_landing_rates: list[float]\n"
    "    average_thruster_activations: list[float]\n"
    "    mean_losses: list[float]\n"
    "\n"
    "\n"
    "def get_device() -> torch.device:\n"
    "    \"\"\"Return the best available device: CUDA > MPS (Apple GPU) > CPU.\"\"\"\n"
    "    if torch.cuda.is_available():\n"
    "        return torch.device('cuda')\n"
    "    if torch.backends.mps.is_available():\n"
    "        return torch.device('mps')\n"
    "    return torch.device('cpu')\n"
    "\n"
    "\n"
    "def set_all_seeds(seed: int) -> None:\n"
    "    \"\"\"Seed Python, NumPy, and PyTorch for reproducible experiments.\"\"\"\n"
    "    random.seed(seed)\n"
    "    np.random.seed(seed)\n"
    "    torch.manual_seed(seed)\n"
    "    if torch.cuda.is_available():\n"
    "        torch.cuda.manual_seed_all(seed)\n"
    "    # MPS uses the CPU RNG; torch.manual_seed above covers it.\n"
    "\n"
    "\n"
    "def make_environment(environment_name: EnvironmentName) -> gym.Env:\n"
    "    \"\"\"Create either the unchanged or stochastic-failure LunarLander version.\"\"\"\n"
    "    base_environment = gym.make('LunarLander-v3')\n"
    "    if environment_name == 'modified':\n"
    "        return StochasticFailureLunarLander(base_environment)\n"
    "    return base_environment\n"
    "\n"
    "\n"
    "def is_safe_landing(observation: np.ndarray, terminated: bool, truncated: bool) -> bool:\n"
    "    \"\"\"Apply the assignment's safe-landing conditions for success-rate tracking.\"\"\"\n"
    "    return bool(\n"
    "        terminated and not truncated\n"
    "        and observation[6] == 1 and observation[7] == 1\n"
    "        and abs(observation[2]) < 0.10\n"
    "        and abs(observation[3]) < 0.10\n"
    "        and abs(observation[4]) < 0.10\n"
    "    )\n"
    "\n"
    "\n"
    "def epsilon_for_episode(episode: int, config: TrainingConfig) -> float:\n"
    "    \"\"\"Linearly reduce random exploration from epsilon_start to epsilon_end.\"\"\"\n"
    "    progress = min(episode / config.epsilon_decay_episodes, 1.0)\n"
    "    return config.epsilon_start + progress * (config.epsilon_end - config.epsilon_start)\n"
    "\n"
    "\n"
    "def collect_validation_states(config: TrainingConfig) -> np.ndarray:\n"
    "    \"\"\"Create one fixed state set used unchanged by all training runs.\"\"\"\n"
    "    state_rng = np.random.default_rng(config.seed + 1)\n"
    "    environment = gym.make('LunarLander-v3')\n"
    "    states: list[np.ndarray] = []\n"
    "    observation, _ = environment.reset(seed=config.seed + 1)\n"
    "    try:\n"
    "        while len(states) < config.validation_state_count:\n"
    "            states.append(np.asarray(observation, dtype=np.float32).copy())\n"
    "            action = int(state_rng.integers(environment.action_space.n))\n"
    "            observation, _, terminated, truncated, _ = environment.step(action)\n"
    "            if terminated or truncated:\n"
    "                observation, _ = environment.reset()\n"
    "    finally:\n"
    "        environment.close()\n"
    "    return np.stack(states)\n"
    "\n"
    "\n"
    "def mean_max_q_value(agent: DQNAgent, validation_states: np.ndarray) -> float:\n"
    "    \"\"\"Return the mean best-action Q-value on the fixed validation state set.\"\"\"\n"
    "    t = torch.as_tensor(validation_states, dtype=torch.float32, device=agent.device)\n"
    "    with torch.no_grad():\n"
    "        return float(agent.online_network(t).max(dim=1).values.mean().item())\n"
    "\n"
    "\n"
    "def build_agent(algorithm: AlgorithmName, dqn_config: DQNConfig, seed: int, device: torch.device) -> DQNAgent:\n"
    "    \"\"\"Create DQN or DDQN with the same architecture and hyperparameters.\"\"\"\n"
    "    if algorithm == 'dqn':\n"
    "        return DQNAgent(dqn_config, seed, device)\n"
    "    if algorithm == 'ddqn':\n"
    "        return DDQNAgent(dqn_config, seed, device)\n"
    "    raise ValueError(f'Unsupported algorithm: {algorithm}')\n"
    "\n"
    "\n"
    "def train_one_experiment(\n"
    "    algorithm: AlgorithmName,\n"
    "    environment_name: EnvironmentName,\n"
    "    training_config: TrainingConfig,\n"
    "    dqn_config: DQNConfig,\n"
    "    validation_states: np.ndarray,\n"
    ") -> tuple[DQNAgent, TrainingMetrics]:\n"
    "    \"\"\"Train one algorithm/environment pair and collect plot-ready metrics.\"\"\"\n"
    "    set_all_seeds(training_config.seed)\n"
    "    device = get_device()\n"
    "    print(f'  Using device: {device}')\n"
    "    environment = make_environment(environment_name)\n"
    "    agent = build_agent(algorithm, dqn_config, training_config.seed, device)\n"
    "    metrics = TrainingMetrics([], [], [], [], [])\n"
    "    recent_successes: list[float] = []\n"
    "    try:\n"
    "        for episode in range(training_config.episodes):\n"
    "            state, _ = environment.reset(seed=training_config.seed + episode)\n"
    "            episode_reward = 0.0\n"
    "            episode_thruster_attempts = 0\n"
    "            episode_losses: list[float] = []\n"
    "            epsilon = epsilon_for_episode(episode, training_config)\n"
    "            success = False\n"
    "            for _ in range(training_config.max_steps_per_episode):\n"
    "                action = agent.select_action(state, epsilon)\n"
    "                if action in (1, 2, 3):\n"
    "                    episode_thruster_attempts += 1\n"
    "                next_state, reward, terminated, truncated, _ = environment.step(action)\n"
    "                done = terminated or truncated\n"
    "                agent.store_transition(state, action, reward, next_state, done)\n"
    "                loss = agent.learn()\n"
    "                if loss is not None:\n"
    "                    episode_losses.append(loss)\n"
    "                episode_reward += reward\n"
    "                state = next_state\n"
    "                if done:\n"
    "                    success = is_safe_landing(state, terminated, truncated)\n"
    "                    break\n"
    "            recent_successes.append(float(success))\n"
    "            if len(recent_successes) > training_config.success_window:\n"
    "                recent_successes.pop(0)\n"
    "            metrics.episode_rewards.append(float(episode_reward))\n"
    "            metrics.average_predicted_q_values.append(mean_max_q_value(agent, validation_states))\n"
    "            metrics.successful_landing_rates.append(float(np.mean(recent_successes)))\n"
    "            metrics.average_thruster_activations.append(float(episode_thruster_attempts))\n"
    "            metrics.mean_losses.append(float(np.mean(episode_losses)) if episode_losses else float('nan'))\n"
    "    finally:\n"
    "        environment.close()\n"
    "    return agent, metrics\n"
    "\n"
    "\n"
    "def save_experiment(\n"
    "    agent: DQNAgent, metrics: TrainingMetrics,\n"
    "    algorithm: AlgorithmName, environment_name: EnvironmentName,\n"
    "    training_config: TrainingConfig, dqn_config: DQNConfig,\n"
    ") -> None:\n"
    "    \"\"\"Save trained weights and numerical metrics for plotting and reporting.\"\"\"\n"
    "    OUTPUT_DIRECTORY.mkdir(exist_ok=True)\n"
    "    stem = f'{algorithm}_{environment_name}'\n"
    "    torch.save(agent.online_network.state_dict(), OUTPUT_DIRECTORY / f'{stem}_model.pt')\n"
    "    np.savez(\n"
    "        OUTPUT_DIRECTORY / f'{stem}_metrics.npz',\n"
    "        episode_rewards=np.asarray(metrics.episode_rewards),\n"
    "        average_predicted_q_values=np.asarray(metrics.average_predicted_q_values),\n"
    "        successful_landing_rates=np.asarray(metrics.successful_landing_rates),\n"
    "        average_thruster_activations=np.asarray(metrics.average_thruster_activations),\n"
    "        mean_losses=np.asarray(metrics.mean_losses),\n"
    "    )\n"
    "    metadata = {\n"
    "        'algorithm': algorithm, 'environment': environment_name,\n"
    "        'training_config': asdict(training_config), 'dqn_config': asdict(dqn_config),\n"
    "    }\n"
    "    with (OUTPUT_DIRECTORY / f'{stem}_metadata.json').open('w', encoding='utf-8') as f:\n"
    "        json.dump(metadata, f, indent=2)\n"
    "\n"
    "\n"
    "def run_training(episodes: int = TrainingConfig.episodes) -> None:\n"
    "    \"\"\"Train all four required agents and save their results.\"\"\"\n"
    "    if episodes <= 0:\n"
    "        raise ValueError('The number of episodes must be positive.')\n"
    "    training_config = TrainingConfig(episodes=episodes)\n"
    "    dqn_config = DQNConfig()\n"
    "    validation_states = collect_validation_states(training_config)\n"
    "    for algorithm in ('dqn', 'ddqn'):\n"
    "        for environment_name in ('original', 'modified'):\n"
    "            print(f'Training {algorithm.upper()} on {environment_name} environment...')\n"
    "            agent, metrics = train_one_experiment(\n"
    "                algorithm, environment_name, training_config, dqn_config, validation_states)\n"
    "            save_experiment(agent, metrics, algorithm, environment_name, training_config, dqn_config)\n"
    "            print(f'  final reward={metrics.episode_rewards[-1]:.1f}, '\n"
    "                  f'final success rate={metrics.successful_landing_rates[-1]:.1%}')\n"
    "\n"
    "print('Training pipeline defined.')"
))

# ── Section 7: Environment Verification ───────────────────────────────────
cells.append(md(
    "## 7 — Environment Verification\n\n"
    "Runs a seeded 20,000-step random policy on the `StochasticFailureLunarLander` "
    "wrapper and asserts the observed failure rate is close to 15%. "
    "Results are saved to `outputs/environment_verification_summary.csv`."
))
cells.append(code(
    "VERIFY_SEED = 2026\n"
    "VERIFY_TOTAL_STEPS = 20_000\n"
    "VERIFY_FUEL_PENALTY = 0.3\n"
    "\n"
    "\n"
    "def run_random_policy_verification() -> StochasticFailureLunarLander:\n"
    "    \"\"\"Run a seeded random policy and return the wrapper's statistics.\"\"\"\n"
    "    action_rng = np.random.default_rng(VERIFY_SEED)\n"
    "    environment = StochasticFailureLunarLander(gym.make('LunarLander-v3'))\n"
    "    environment.reset(seed=VERIFY_SEED)\n"
    "    for _ in range(VERIFY_TOTAL_STEPS):\n"
    "        selected_action = int(action_rng.integers(environment.action_space.n))\n"
    "        _, _, terminated, truncated, _ = environment.step(selected_action)\n"
    "        if terminated or truncated:\n"
    "            environment.reset()\n"
    "    return environment\n"
    "\n"
    "\n"
    "def verify_internal_statistics(environment: StochasticFailureLunarLander) -> None:\n"
    "    \"\"\"Assert the wrapper's aggregate fuel-penalty accounting is correct.\"\"\"\n"
    "    stats = environment.statistics\n"
    "    expected = stats.attempted_thruster_actions * VERIFY_FUEL_PENALTY\n"
    "    assert np.isclose(stats.attempted_fuel_penalty, expected)\n"
    "\n"
    "\n"
    "def write_summary_csv(environment: StochasticFailureLunarLander) -> Path:\n"
    "    \"\"\"Save report-ready aggregate verification evidence to a CSV file.\"\"\"\n"
    "    OUTPUT_DIRECTORY.mkdir(exist_ok=True)\n"
    "    output_path = OUTPUT_DIRECTORY / 'environment_verification_summary.csv'\n"
    "    stats = environment.statistics\n"
    "    with output_path.open('w', newline='', encoding='utf-8') as f:\n"
    "        writer = csv.writer(f)\n"
    "        writer.writerow(['metric', 'value'])\n"
    "        writer.writerow(['random_policy_steps',        VERIFY_TOTAL_STEPS])\n"
    "        writer.writerow(['attempted_thruster_actions', stats.attempted_thruster_actions])\n"
    "        writer.writerow(['failed_thruster_actions',    stats.failed_thruster_actions])\n"
    "        writer.writerow(['observed_failure_rate',      stats.observed_failure_rate])\n"
    "        writer.writerow(['total_fuel_penalty',         stats.attempted_fuel_penalty])\n"
    "        writer.writerow(['safe_landing_bonus_count',   stats.safe_landing_bonus_count])\n"
    "    return output_path\n"
    "\n"
    "\n"
    "def run_verification() -> None:\n"
    "    \"\"\"Run the random-policy verification and close the Box2D environment.\"\"\"\n"
    "    environment = run_random_policy_verification()\n"
    "    try:\n"
    "        verify_internal_statistics(environment)\n"
    "        output_path = write_summary_csv(environment)\n"
    "        stats = environment.statistics\n"
    "        print('Environment verification complete')\n"
    "        print(f'Random-policy steps:            {VERIFY_TOTAL_STEPS}')\n"
    "        print(f'Attempted thruster actions:     {stats.attempted_thruster_actions}')\n"
    "        print(f'Failed thruster actions:        {stats.failed_thruster_actions}')\n"
    "        print(f'Observed failure rate:          {stats.observed_failure_rate:.2%}')\n"
    "        print(f'Total fuel penalty:             {stats.attempted_fuel_penalty:.1f}')\n"
    "        print(f'Safe-landing bonuses:           {stats.safe_landing_bonus_count}')\n"
    "        print(f'CSV written to:                 {output_path}')\n"
    "    finally:\n"
    "        environment.close()\n"
    "\n"
    "print('Verification functions defined.')"
))

# ── Section 8: Plotting ────────────────────────────────────────────────────
cells.append(md(
    "## 8 — Results Plotting\n\n"
    "Loads the four `.npz` metrics files produced by training and produces a "
    "2×2 comparison figure saved to `outputs/drl_performance_comparison.png`.\n\n"
    "> **Run after training completes.**"
))
cells.append(code(
    "def run_plot() -> None:\n"
    "    \"\"\"Load saved metrics and produce the four-panel comparison figure.\"\"\"\n"
    "    runs = [\n"
    "        ('dqn_original',  'DQN - Original',  'blue'),\n"
    "        ('ddqn_original', 'DDQN - Original', 'cyan'),\n"
    "        ('dqn_modified',  'DQN - Modified',  'red'),\n"
    "        ('ddqn_modified', 'DDQN - Modified', 'orange'),\n"
    "    ]\n"
    "    fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n"
    "    for stem, label, color in runs:\n"
    "        data = np.load(OUTPUT_DIRECTORY / f'{stem}_metrics.npz')\n"
    "        axes[0, 0].plot(data['episode_rewards'],              label=label, color=color, alpha=0.6)\n"
    "        axes[0, 1].plot(data['average_predicted_q_values'],   label=label, color=color)\n"
    "        axes[1, 0].plot(data['successful_landing_rates'],     label=label, color=color)\n"
    "        axes[1, 1].plot(data['average_thruster_activations'], label=label, color=color, alpha=0.6)\n"
    "    titles = [\n"
    "        '1. Episode Reward vs Episode',\n"
    "        '2. Avg Predicted Q-value (Validation Set)',\n"
    "        '3. Landing Success Rate (100-Ep Moving Avg)',\n"
    "        '4. Avg Thruster Activations per Episode',\n"
    "    ]\n"
    "    for ax, title in zip(axes.flat, titles):\n"
    "        ax.set_title(title, fontsize=12, fontweight='bold')\n"
    "        ax.set_xlabel('Episode')\n"
    "        ax.grid(True, linestyle='--', alpha=0.5)\n"
    "        ax.legend()\n"
    "    plt.tight_layout()\n"
    "    out_path = OUTPUT_DIRECTORY / 'drl_performance_comparison.png'\n"
    "    plt.savefig(out_path, dpi=300)\n"
    "    print(f'Plot saved to: {out_path}')\n"
    "    plt.show()\n"
    "\n"
    "print('Plotting function defined.')"
))

# ── Run Experiments ────────────────────────────────────────────────────────
cells.append(md(
    "---\n"
    "## ▶ Run Experiments\n\n"
    "Execute the cells below one at a time. "
    "Run **Step 1** first, then **Step 2** (smoke test), "
    "then **Step 3** (full training), then **Step 4** (plots)."
))

cells.append(md("### Step 1 — Verify the custom environment wrapper"))
cells.append(code("run_verification()"))

cells.append(md(
    "### Step 2 — Smoke test (50 episodes)\n\n"
    "Runs all 4 experiments for 50 episodes to confirm the full pipeline works."
))
cells.append(code("run_training(episodes=50)"))

cells.append(md(
    "### Step 3 — Full training (700 episodes)\n\n"
    "> ⏱ Estimated time: ~15–30 min on Apple MPS / ~20–40 min on Colab T4 / ~60–90 min on CPU."
))
cells.append(code("run_training()  # default 700 episodes"))

cells.append(md("### Step 4 — Plot results"))
cells.append(code("run_plot()"))

# ── Assemble notebook ──────────────────────────────────────────────────────
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (drl_mac_env)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.9.0"
        }
    },
    "cells": cells,
}

output_path = Path("drl_assignment2.ipynb")
output_path.write_text(json.dumps(notebook, indent=1), encoding="utf-8")
print(f"Notebook written: {output_path}  ({output_path.stat().st_size // 1024} KB)")
print(f"Total cells: {len(cells)}")
